version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/examples/hello-mysql"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/examples/hello-simple"
    schedule:
      interval: "weekly"